[2025-05-21 20:17:59,920 ] 20 root - INFO - Initiate the data ingestion
[2025-05-21 20:18:03,949 ] 65 root - INFO - Performed train test split on the dataframe
[2025-05-21 20:18:03,949 ] 67 root - INFO - Exited split_data_as_train_test method of Data_Ingestion class
[2025-05-21 20:18:03,949 ] 75 root - INFO - Exporting train and test file path.
[2025-05-21 20:18:03,991 ] 84 root - INFO - Exported train and test file path.
[2025-05-21 20:18:03,991 ] 22 root - INFO - Data Initiation Completed
[2025-05-21 20:18:03,998 ] 26 root - INFO - Initiate the data Validation
[2025-05-21 20:18:04,100 ] 32 root - INFO - Required number of columns:2
[2025-05-21 20:18:04,100 ] 33 root - INFO - Data frame has columns:31
[2025-05-21 20:18:04,100 ] 32 root - INFO - Required number of columns:2
[2025-05-21 20:18:04,100 ] 33 root - INFO - Data frame has columns:31
[2025-05-21 20:18:04,211 ] 28 root - INFO - data Validation Completed
[2025-05-21 20:18:04,211 ] 31 root - INFO - data Transformation started
[2025-05-21 20:18:04,211 ] 63 root - INFO - Entered initiate_data_transformation method of DataTransformation class
[2025-05-21 20:18:04,211 ] 65 root - INFO - Starting data transformation
[2025-05-21 20:18:04,226 ] 48 root - INFO - Entered get_data_trnasformer_object method of Trnasformation class
[2025-05-21 20:18:04,226 ] 53 root - INFO - Initialise KNNImputer with {'missing_values': nan, 'n_neighbors': 3, 'weights': 'uniform'}
[2025-05-21 20:18:04,251 ] 46 root - INFO - Entered the save_object method of MainUtils class
[2025-05-21 20:18:04,251 ] 50 root - INFO - Exited the save_object method of MainUtils class
[2025-05-21 20:18:04,251 ] 46 root - INFO - Entered the save_object method of MainUtils class
[2025-05-21 20:18:04,251 ] 50 root - INFO - Exited the save_object method of MainUtils class
[2025-05-21 20:18:04,251 ] 35 root - INFO - data Transformation completed
[2025-05-21 20:18:04,251 ] 37 root - INFO - Model Training sstared
[2025-05-21 20:21:56,560 ] 868 urllib3.connectionpool - WARNING - Retrying (Retry(total=6, connect=6, read=7, redirect=7, status=7)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000023DB35731C0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /api/2.0/mlflow/runs/create
[2025-05-21 20:22:05,077 ] 868 urllib3.connectionpool - WARNING - Retrying (Retry(total=5, connect=5, read=7, redirect=7, status=7)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000023DB3572F20>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /api/2.0/mlflow/runs/create
[2025-05-21 20:22:18,036 ] 868 urllib3.connectionpool - WARNING - Retrying (Retry(total=4, connect=4, read=7, redirect=7, status=7)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000023DB5AB5600>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /api/2.0/mlflow/runs/create
[2025-05-21 20:22:38,430 ] 868 urllib3.connectionpool - WARNING - Retrying (Retry(total=3, connect=3, read=7, redirect=7, status=7)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000023DB35724A0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /api/2.0/mlflow/runs/create
[2025-05-21 20:23:14,798 ] 868 urllib3.connectionpool - WARNING - Retrying (Retry(total=2, connect=2, read=7, redirect=7, status=7)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000023DB3573E80>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /api/2.0/mlflow/runs/create
[2025-05-21 20:24:23,630 ] 868 urllib3.connectionpool - WARNING - Retrying (Retry(total=1, connect=1, read=7, redirect=7, status=7)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000023DB3572EC0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /api/2.0/mlflow/runs/create
[2025-05-21 20:26:27,682 ] 868 urllib3.connectionpool - WARNING - Retrying (Retry(total=0, connect=0, read=7, redirect=7, status=7)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000023DB3571540>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /api/2.0/mlflow/runs/create
